//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

using System.Xml.Serialization;

namespace server.TextLoader.Models {
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(TypeName="TEI.2Type")]
    [XmlRoot("TEI.2", Namespace="", IsNullable=false)]
    public partial class TEI2Type {
        
        private teiHeaderType teiHeaderField;
        
        private textType textField;
        
        /// <remarks/>
        public teiHeaderType teiHeader {
            get {
                return this.teiHeaderField;
            }
            set {
                this.teiHeaderField = value;
            }
        }
        
        /// <remarks/>
        public textType text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class teiHeaderType {
        
        private fileDescType fileDescField;
        
        private refsDeclType[] encodingDescField;
        
        private profileDescType profileDescField;
        
        private revisionDescType revisionDescField;
        
        private string typeField;
        
        private string statusField;
        
        /// <remarks/>
        public fileDescType fileDesc {
            get {
                return this.fileDescField;
            }
            set {
                this.fileDescField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("refsDecl", IsNullable=false)]
        public refsDeclType[] encodingDesc {
            get {
                return this.encodingDescField;
            }
            set {
                this.encodingDescField = value;
            }
        }
        
        /// <remarks/>
        public profileDescType profileDesc {
            get {
                return this.profileDescField;
            }
            set {
                this.profileDescField = value;
            }
        }
        
        /// <remarks/>
        public revisionDescType revisionDesc {
            get {
                return this.revisionDescField;
            }
            set {
                this.revisionDescField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fileDescType {
        
        private titleStmtType titleStmtField;
        
        private publicationStmtType publicationStmtField;
        
        private sourceDescType sourceDescField;
        
        /// <remarks/>
        public titleStmtType titleStmt {
            get {
                return this.titleStmtField;
            }
            set {
                this.titleStmtField = value;
            }
        }
        
        /// <remarks/>
        public publicationStmtType publicationStmt {
            get {
                return this.publicationStmtField;
            }
            set {
                this.publicationStmtField = value;
            }
        }
        
        /// <remarks/>
        public sourceDescType sourceDesc {
            get {
                return this.sourceDescField;
            }
            set {
                this.sourceDescField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class titleStmtType {
        
        private titleStmtTypeTitle[] titleField;
        
        private authorType authorField;
        
        private editorType editorField;
        
        private string sponsorField;
        
        private string principalField;
        
        private object[] respStmtField;
        
        private funderType funderField;
        
        /// <remarks/>
        [XmlElement("title")]
        public titleStmtTypeTitle[] title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public authorType author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public editorType editor {
            get {
                return this.editorField;
            }
            set {
                this.editorField = value;
            }
        }
        
        /// <remarks/>
        public string sponsor {
            get {
                return this.sponsorField;
            }
            set {
                this.sponsorField = value;
            }
        }
        
        /// <remarks/>
        public string principal {
            get {
                return this.principalField;
            }
            set {
                this.principalField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("name", typeof(respStmtTypeName), IsNullable=false)]
        [XmlArrayItem("resp", typeof(respStmtTypeResp), IsNullable=false)]
        public object[] respStmt {
            get {
                return this.respStmtField;
            }
            set {
                this.respStmtField = value;
            }
        }
        
        /// <remarks/>
        public funderType funder {
            get {
                return this.funderField;
            }
            set {
                this.funderField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class titleStmtTypeTitle {
        
        private string typeField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class div1Type {
        
        private string headField;
        
        private milestoneType[] milestoneField;
        
        private pType[] pField;
        
        private string typeField;
        
        private string nField;
        
        private string orgField;
        
        private string sampleField;
        
        /// <remarks/>
        public string head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("milestone")]
        public milestoneType[] milestone {
            get {
                return this.milestoneField;
            }
            set {
                this.milestoneField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("p")]
        public pType[] p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string org {
            get {
                return this.orgField;
            }
            set {
                this.orgField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string sample {
            get {
                return this.sampleField;
            }
            set {
                this.sampleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class milestoneType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string nField;
        
        private string unitField;
        
        private string placeField;
        
        private string anchoredField;
        
        /// <remarks/>
        [XmlElement("foreign", typeof(foreignType))]
        [XmlElement("hi", typeof(hiType))]
        [XmlElement("note", typeof(noteType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string anchored {
            get {
                return this.anchoredField;
            }
            set {
                this.anchoredField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class foreignType {
        
        private foreignType[] foreignField;
        
        private string[] textField;
        
        private string langField;
        
        private string rendField;
        
        /// <remarks/>
        [XmlElement("foreign")]
        public foreignType[] foreign {
            get {
                return this.foreignField;
            }
            set {
                this.foreignField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string rend {
            get {
                return this.rendField;
            }
            set {
                this.rendField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class hiType {
        
        private foreignType[] foreignField;
        
        private string[] textField;
        
        private string rendField;
        
        private string langField;
        
        /// <remarks/>
        [XmlElement("foreign")]
        public foreignType[] foreign {
            get {
                return this.foreignField;
            }
            set {
                this.foreignField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string rend {
            get {
                return this.rendField;
            }
            set {
                this.rendField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string lang {
            get {
                return this.langField;
            }
            set {
                this.langField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class noteType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string placeField;
        
        private string anchoredField;
        
        private string nField;
        
        private string unitField;
        
        /// <remarks/>
        [XmlElement("foreign", typeof(foreignType))]
        [XmlElement("hi", typeof(hiType))]
        [XmlElement("note", typeof(noteType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string anchored {
            get {
                return this.anchoredField;
            }
            set {
                this.anchoredField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class pType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        /// <remarks/>
        [XmlElement("abbr", typeof(abbrType))]
        [XmlElement("milestone", typeof(milestoneType))]
        [XmlElement("name", typeof(pTypeName))]
        [XmlElement("note", typeof(noteType))]
        [XmlElement("num", typeof(pTypeNum))]
        [XmlElement("persName", typeof(pTypePersName))]
        [XmlElement("quote", typeof(pTypeQuote))]
        [XmlElement("reg", typeof(pTypeReg))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class abbrType {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string expanField;
        
        private string placeField;
        
        private string anchoredField;
        
        private string nField;
        
        private string unitField;
        
        /// <remarks/>
        [XmlElement("foreign", typeof(foreignType))]
        [XmlElement("hi", typeof(hiType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string expan {
            get {
                return this.expanField;
            }
            set {
                this.expanField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string anchored {
            get {
                return this.anchoredField;
            }
            set {
                this.anchoredField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class pTypeName {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string placeField;
        
        private string anchoredField;
        
        private string nField;
        
        private string unitField;
        
        /// <remarks/>
        [XmlElement("foreign", typeof(foreignType))]
        [XmlElement("hi", typeof(hiType))]
        [XmlElement("note", typeof(noteType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string anchored {
            get {
                return this.anchoredField;
            }
            set {
                this.anchoredField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class pTypeNum {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string placeField;
        
        private string anchoredField;
        
        private string nField;
        
        private string unitField;
        
        /// <remarks/>
        [XmlElement("foreign", typeof(foreignType))]
        [XmlElement("hi", typeof(hiType))]
        [XmlElement("note", typeof(noteType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string anchored {
            get {
                return this.anchoredField;
            }
            set {
                this.anchoredField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class pTypePersName {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string placeField;
        
        private string anchoredField;
        
        private string nField;
        
        private string unitField;
        
        /// <remarks/>
        [XmlElement("foreign", typeof(foreignType))]
        [XmlElement("hi", typeof(hiType))]
        [XmlElement("note", typeof(noteType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string anchored {
            get {
                return this.anchoredField;
            }
            set {
                this.anchoredField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class pTypeQuote {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string placeField;
        
        private string anchoredField;
        
        private string nField;
        
        private string unitField;
        
        /// <remarks/>
        [XmlElement("foreign", typeof(foreignType))]
        [XmlElement("hi", typeof(hiType))]
        [XmlElement("note", typeof(noteType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string anchored {
            get {
                return this.anchoredField;
            }
            set {
                this.anchoredField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(AnonymousType=true)]
    public partial class pTypeReg {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string placeField;
        
        private string anchoredField;
        
        private string nField;
        
        private string unitField;
        
        /// <remarks/>
        [XmlElement("foreign", typeof(foreignType))]
        [XmlElement("hi", typeof(hiType))]
        [XmlElement("note", typeof(noteType))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string anchored {
            get {
                return this.anchoredField;
            }
            set {
                this.anchoredField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bodyType {
        
        private bodyTypeHead headField;
        
        private milestoneType[] milestoneField;
        
        private pType[] pField;
        
        private div1Type[] div1Field;
        
        /// <remarks/>
        public bodyTypeHead head {
            get {
                return this.headField;
            }
            set {
                this.headField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("milestone")]
        public milestoneType[] milestone {
            get {
                return this.milestoneField;
            }
            set {
                this.milestoneField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("p")]
        public pType[] p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [XmlElement("div1")]
        public div1Type[] div1 {
            get {
                return this.div1Field;
            }
            set {
                this.div1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum bodyTypeHead {
        
        /// <remarks/>
        [XmlEnum("PRO T. ANNIO MILONE ORATIO")]
        PROTANNIOMILONEORATIO,
        
        /// <remarks/>
        [XmlEnum("PRO M. MARCELLO ORATIO")]
        PROMMARCELLOORATIO,
        
        /// <remarks/>
        [XmlEnum("PRO Q. LIGARIO ORATIO")]
        PROQLIGARIOORATIO,
        
        /// <remarks/>
        [XmlEnum("PRO REGE DEIOTARO AD\n                        C. CAESAREM ORATIO\n                 " +
            "   ")]
        PROREGEDEIOTAROADCCAESAREMORATIO,
        
        /// <remarks/>
        [XmlEnum("Philippicae Orationes in M. Antonium")]
        PhilippicaeOrationesinMAntonium,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class textType {
        
        private bodyType bodyField;
        
        private textType[] groupField;
        
        private string nField;
        
        /// <remarks/>
        public bodyType body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("text", IsNullable=false)]
        public textType[] group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class changeType {
        
        private string dateField;
        
        private object[] respStmtField;
        
        private itemType itemField;
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("name", typeof(respStmtTypeName), IsNullable=false)]
        [XmlArrayItem("resp", typeof(respStmtTypeResp), IsNullable=false)]
        public object[] respStmt {
            get {
                return this.respStmtField;
            }
            set {
                this.respStmtField = value;
            }
        }
        
        /// <remarks/>
        public itemType item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum respStmtTypeName {
        
        /// <remarks/>
        [XmlEnum("Lisa Cerrato")]
        LisaCerrato,
        
        /// <remarks/>
        [XmlEnum("William Merrill")]
        WilliamMerrill,
        
        /// <remarks/>
        [XmlEnum("Elli Mylonas")]
        ElliMylonas,
        
        /// <remarks/>
        [XmlEnum("David Smith")]
        DavidSmith,
        
        /// <remarks/>
        CJSU,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [XmlType(AnonymousType=true)]
    public enum respStmtTypeResp {
        
        /// <remarks/>
        [XmlEnum("Prepared under the supervision of")]
        Preparedunderthesupervisionof,
        
        /// <remarks/>
        [XmlEnum("ed.")]
        ed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class itemType {
        
        private string quoteField;
        
        private string nameField;
        
        private string regField;
        
        private string[] textField;
        
        /// <remarks/>
        public string quote {
            get {
                return this.quoteField;
            }
            set {
                this.quoteField = value;
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string reg {
            get {
                return this.regField;
            }
            set {
                this.regField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class revisionDescType {
        
        private changeType changeField;
        
        /// <remarks/>
        public changeType change {
            get {
                return this.changeField;
            }
            set {
                this.changeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class languageType {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class langUsageType {
        
        private languageType[] languageField;
        
        private string defaultField;
        
        /// <remarks/>
        [XmlElement("language")]
        public languageType[] language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class profileDescType {
        
        private langUsageType langUsageField;
        
        /// <remarks/>
        public langUsageType langUsage {
            get {
                return this.langUsageField;
            }
            set {
                this.langUsageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stateType {
        
        private string delimField;
        
        private string unitField;
        
        private string nField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string delim {
            get {
                return this.delimField;
            }
            set {
                this.delimField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string unit {
            get {
                return this.unitField;
            }
            set {
                this.unitField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class refsDeclType {
        
        private stateType[] stateField;
        
        private string doctypeField;
        
        private string nField;
        
        /// <remarks/>
        [XmlElement("state")]
        public stateType[] state {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string doctype {
            get {
                return this.doctypeField;
            }
            set {
                this.doctypeField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class seriesType {
        
        private string titleField;
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class imprintType {
        
        private string pubPlaceField;
        
        private string publisherField;
        
        private string dateField;
        
        /// <remarks/>
        public string pubPlace {
            get {
                return this.pubPlaceField;
            }
            set {
                this.pubPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        public string date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class monogrType {
        
        private string authorField;
        
        private string titleField;
        
        private editorType editorField;
        
        private imprintType imprintField;
        
        /// <remarks/>
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        public editorType editor {
            get {
                return this.editorField;
            }
            set {
                this.editorField = value;
            }
        }
        
        /// <remarks/>
        public imprintType imprint {
            get {
                return this.imprintField;
            }
            set {
                this.imprintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class editorType {
        
        private string roleField;
        
        private string nField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class biblStructType {
        
        private monogrType monogrField;
        
        private seriesType seriesField;
        
        private string defaultField;
        
        /// <remarks/>
        public monogrType monogr {
            get {
                return this.monogrField;
            }
            set {
                this.monogrField = value;
            }
        }
        
        /// <remarks/>
        public seriesType series {
            get {
                return this.seriesField;
            }
            set {
                this.seriesField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sourceDescType {
        
        private biblStructType biblStructField;
        
        private string defaultField;
        
        /// <remarks/>
        public biblStructType biblStruct {
            get {
                return this.biblStructField;
            }
            set {
                this.biblStructField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string @default {
            get {
                return this.defaultField;
            }
            set {
                this.defaultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class availabilityType {
        
        private string pField;
        
        private itemType[] listField;
        
        private string statusField;
        
        /// <remarks/>
        public string p {
            get {
                return this.pField;
            }
            set {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [XmlArrayItem("item", IsNullable=false)]
        public itemType[] list {
            get {
                return this.listField;
            }
            set {
                this.listField = value;
            }
        }
        
        /// <remarks/>
        [XmlAttribute()]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class publicationStmtType {
        
        private string publisherField;
        
        private string pubPlaceField;
        
        private string authorityField;
        
        private availabilityType availabilityField;
        
        /// <remarks/>
        public string publisher {
            get {
                return this.publisherField;
            }
            set {
                this.publisherField = value;
            }
        }
        
        /// <remarks/>
        public string pubPlace {
            get {
                return this.pubPlaceField;
            }
            set {
                this.pubPlaceField = value;
            }
        }
        
        /// <remarks/>
        public string authority {
            get {
                return this.authorityField;
            }
            set {
                this.authorityField = value;
            }
        }
        
        /// <remarks/>
        public availabilityType availability {
            get {
                return this.availabilityField;
            }
            set {
                this.availabilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class funderType {
        
        private string nField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class authorType {
        
        private string nField;
        
        private string valueField;
        
        /// <remarks/>
        [XmlAttribute()]
        public string n {
            get {
                return this.nField;
            }
            set {
                this.nField = value;
            }
        }
        
        /// <remarks/>
        [XmlText()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
